name: Webhooks CRON

on:
  schedule:
    # Runs every minute
    - cron: '*/5 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dispatch_webhooks:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook Deliveries
        run: |
          # Make sure to replace this with your actual production domain!
          # If you have an API secret, you can pass it via headers.
          curl -X GET "https://ourmenuos.online/api/cron/webhooks"
